Repository HomeLog/homelog-client, pull requests merged in 2024-08, with the labels that each got.

#57 chore: 프로필 이미지 모양 수정
  src/app/profile/_containers/ProfileImages.tsx
Labels: enhancement

#75 fix: 방명록 남기기 페이지 로그인 요구 비활성화
  src/app/guest-book/[id]/page.tsx
  src/app/guest-book/create/_hook/useGuestBookLink.ts
  src/app/guest-book/create/page.tsx
Labels: bug

#76 fix: 작성된 방명록의 경우 방명록 상세 페이지로 이동
  src/app/guest-book/[id]/leave-message/page.tsx
  src/app/guest-book/_utils/image.util.ts
Labels: bug

#83 docs: 리드미 업데이트
  README.md
Labels: documentation

#94 fix: 로그인 후 뒤로 가기시 콜백 URL 다시 호출되는 현상 수정
  src/app/users/kakao/callback/page.tsx
Labels: bug

#95 리드미 업데이트
  README.md
Labels: documentation

#96 docs: 리드미 업데이트
  README.md
Labels: documentation

#98 docs: 리드미 업데이트
  README.md
Labels: documentation

#99 docs: 리드미 업데이트
  README.md
Labels: documentation
